--- drivers/input/touchscreen/Makefile	2013-04-19 11:37:14.000000000 +0200
+++ drivers/input/touchscreen/Makefile	2014-08-29 08:16:14.108240000 +0200
@@ -69,3 +69,14 @@
 obj-$(CONFIG_TOUCHSCREEN_MSM_LEGACY)		+= msm_touch.o
 obj-$(CONFIG_TOUCHSCREEN_CY8C_TS)	+= cy8c_ts.o
 obj-$(CONFIG_TOUCHSCREEN_CYTTSP_I2C)       += cyttsp-i2c.o
+obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI4)	+= synaptics_i2c_rmi4_jena.o
+#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI4)   += ISSP/
+obj-$(CONFIG_TOUCHSCREEN_MELFAS)   += melfas_ts.o mms100_download.o
+obj-$(CONFIG_TOUCHSCREEN_ZINITIX)   += zinitix_touch.o
+obj-$(CONFIG_TOUCHSCREEN_ZINITIX_TREBON)   += zinitix_touch_trebon.o
+obj-$(CONFIG_TOUCHSCREEN_ZINITIX_AMAZING)   += zinitix_touch_amazing.o
+obj-$(CONFIG_TOUCHSCREEN_ZINITIX_GEIM)   += zinitix_touch_geim.o
+obj-$(CONFIG_TOUCHSCREEN_MELFAS_TS)        += melfas_mcs7000.o mcs7000_download.o
+obj-$(CONFIG_TOUCHSCREEN_MELFAS_KYLE)   += melfas_ts.o MMS100S_ISC_Updater_V01.o MMS100S_ISC_Updater_Customize.o
+obj-$(CONFIG_TOUCHSCREEN_MELFAS_FIRMWARE_UPDATE)        += mms100_ISC_download.o
+
